// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type MovieInput struct {
	Director    string `json:"director"`
	Description string `json:"description"`
	Name        string `json:"name"`
	Rank        int    `json:"rank"`
	Parent      *int   `json:"parent"`
}
